- name: Clone frontend repository
  git:
    repo: "{{ frontend_repo_url }}"
    dest: /opt/frontend
    version: main

- name: Set ownership to azureuser for frontend app
  file:
    path: /opt/frontend
    owner: azureuser
    group: azureuser
    recurse: yes

- name: Install frontend dependencies
  npm:
    path: /opt/frontend/frontend
    state: present

- name: Create frontend environment file
  copy:
    dest: /opt/frontend/frontend/.env
    content: |
      NEXT_PUBLIC_API_URL={{ backend_api_url }}

- name: Build frontend
  shell: |
    cd /opt/frontend/frontend
    npm run build
  args:
    executable: /bin/bash

- name: Start frontend app using PM2
  shell: |
    cd /opt/frontend/frontend
    pm2 start npm --name book-review-frontend -- run dev
  args:
    executable: /bin/bash

- name: Save PM2 process list
  shell: pm2 save