- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install essential packages
  apt:
    name:
      - curl
      - git
      - unzip
      - mysql-client
    state: present

- name: Install Node.js
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
    sudo apt-get install -y nodejs
  args:
    executable: /bin/bash

- name: Install PM2 globally
  npm:
    name: pm2
    global: yes
    state: present

- name: Setup PM2 to start on boot
  shell: |
    pm2 startup systemd -u {{ ansible_user }} --hp /home/{{ ansible_user }}
  args:
    executable: /bin/bash