- name: Clone backend repository
  git:
    repo: "{{ backend_repo_url }}"
    dest: /opt/backend
    version: main
    force: yes

- name: Set ownership to azureuser for backend app
  file:
    path: /opt/backend
    owner: azureuser
    group: azureuser
    recurse: yes

- name: Install backend dependencies
  npm:
    path: /opt/backend/backend
    state: present

- name: Create PM2 ecosystem.config.js for backend
  copy:
    dest: /opt/backend/backend/ecosystem.config.js
    content: |
      module.exports = {
        apps : [{
          name: 'book-review-backend',
          script: 'src/server.js',
          env: {
            DB_HOST: '{{ db_host }}',
            DB_USER: '{{ db_user }}',
            DB_PASS: '{{ db_password }}',
            DB_NAME: '{{ db_name }}',
            DB_DIALECT: 'mysql',
            JWT_SECRET: '{{ jwt_secret }}',
            ALLOWED_ORIGINS: '{{ allowed_origins }}'
          }
        }]
      };
  notify: Restart backend with PM2

- name: Ensure pip is installed
  apt:
    name: python3-pip
    state: present
  become: yes

- name: Install PyMySQL library for Ansible MySQL modules
  pip:
    name: PyMySQL
    executable: pip3

- name: Install MySQL client (if not already installed)
  apt:
    name: mysql-client
    state: present
  become: yes

- name: Create database if not exists using mysql command
  shell: |
    mysql -h {{ db_host }} -u {{ db_user }} -p{{ db_password }} -e "CREATE DATABASE IF NOT EXISTS {{ db_name }};"
  args:
    executable: /bin/bash
  environment:
    MYSQL_PWD: "{{ db_password }}"