- name: Common configuration for all servers
  hosts: all
  become: yes
  roles:
    - common

- name: Setup Backend
  hosts: backend
  become: yes
  roles:
    - backend

- name: Setup Frontend
  hosts: frontend
  become: yes
  roles:
    - frontend